# config.yaml

project:
  name: DeepSign
  seed: 42
  device: "cpu"  # or "cuda"

data:
  dataset_name: IDCAR 2011
  train_dir: "../data/sign_data/train"
  #val_dir: "../data/sign_data/val"
  test_dir: "../data/sign_data/test"
  train_pairs: "../data/sign_data/train_data.csv"
  test_pairs: "../data/sign_data/test_data.csv"
  train_serialized_path: "../data/train_pairs.tfrecord"
  HuggingFace:
    train_repo_id: "23daVinci/IDCAR_Signature_Verification_Dataset_Serialized"
    train_filename: "train_pairs.tfrecord"
  img_height: 128
  img_width: 256
  batch_size: 32
  num_workers: 1
  shuffle_buffer_size: 2048
  TFRecord_buffer_size: 33554432  # 32 MB

model:
  architecture: "SiameseNet"
  embedding_dim: 128
  pretrained: False
  save_path: "../trained_model"

training:
  val_fraction: 0.1
  epochs: 1
  learning_rate: 0.0001
  loss: 'binary_crossentropy'
  optimizer: "adam"
  weight_decay: 1e-5
  early_stopping: True
  patience: 5
  lr_scheduler: "StepLR"
  step_size: 10
  gamma: 0.1

logging:
  log_dir: "logs/"
  use_wandb: True
  wandb_project: "signature-verification"

checkpoint:
  save_dir: "checkpoints/"
  save_best_only: True
  monitor: "val_loss"

augmentation:
  horizontal_flip: True
  rotation_range: 15
  brightness_range: [0.8, 1.2]
